# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1affcac8cedbab053c19a387065f6a2ddbf08446d9ab35f9285dd4c5fc9e0a5d19d0baef78acc1c7092c9882902c6b1daa69bac2ef9aa3bf6f8622ac11f6c35

test:
  secret_key_base: bef65225b9648a6452af46c7add53195161b88000892c7cc56fcd2d04956ee770250f17451022903faf70cfd847a82ab80358aefdb057dc113b3ffc80ad92755

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
